jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t an1ta/securesnap:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.13.0
        with:
          image-ref: an1ta/securesnap:latest
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library

      - name: Push image to Docker Hub
        run: docker push an1ta/securesnap:latest
